module.exports = Object.freeze({
	MAX_HP: 50,
	LVL: [
		{ REQUIRED_EXP: 5 },
		{ REQUIRED_EXP: 15 },
		{ REQUIRED_EXP: 30 },
		{ REQUIRED_EXP: 55 },
		{ REQUIRED_EXP: 75 },
		{ REQUIRED_EXP: 95 },
		{ REQUIRED_EXP: 125 },
		{ REQUIRED_EXP: 145 },
		{ REQUIRED_EXP: 170 },
		{ REQUIRED_EXP: 200 },
		{ REQUIRED_EXP: 245 },
	],
	TASK_DIFFICULTY: {
		EASY: 1,
		MEDIUM: 2,
		HARD: 3,
	},
	TASK_TYPE: {
		TODO: 'TODO',
		SCHEDULE: 'SCHEDULE',
		HABIT: 'HABIT',
	},
	PLAYER_REDUCER: {
		CHANGE_EXP: 'EXP',
		CHANGE_HP: 'HP',
	},
	TASK_REDUCER: {
		ADD_TASK: 'ADD TASK',
		REMOVE_TASK: 'REMOVE TASK',
		FILTER_TASK: 'filter',
		EDIT_TASK: 'EDIT TASK',
		SET_ACTIVE_CATEGORY: 'ACTIVE CATEGORY',
	},
	COMPLITED_TASKS: {
		SUCCESS: 'SUCCESS',
		FAIL: 'FAIL',
	},
	LOCAL_STORAGE_REDUCER: {
		UPDATE_VISIT_DATE: 'UPDATE VISIT TIME',
		SET_COMPLITED_TASKS: 'COMPLITED TASKS',
		LAST_VISIT_DATE: 'LAST VISIT DATE',
		DAYS_STREAK: 'DAYS STREAK',
		MAX_DAYS_STREAK: 'MAX DAYS STREAK',
		PLAYER_DATA: 'PLAYER DATA',
	},
});
